### ISSUE TITLE
Getting an error..

### ISSUE THREAD

**Issue by blynnXPO** [OpenSTFoundation/ost-sdk-ruby#10]
I'm trying to run this command `ostUsersObject = OSTSdk::Saas::Users.new(environment, credentials)` and it's pulling back the following error NameError: uninitialized constant OSTSdk::Saas.

**Comment by puneet-khushwani-eth** [comment]
require('ost-sdk-ruby')

from irb console would load our module after which above method should work.

**Comment by blynnXPO** [comment]
I got this error:

`LoadError: cannot load such file -- rack
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/ost-sdk-ruby-0.9.2/lib/ost-sdk-ruby/util/http_helper.rb:12:in `<class:HTTPHelper>'
	from /Library/Ruby/Gems/2.3.0/gems/ost-sdk-ruby-0.9.2/lib/ost-sdk-ruby/util/http_helper.rb:5:in `<module:Util>'
	from /Library/Ruby/Gems/2.3.0/gems/ost-sdk-ruby-0.9.2/lib/ost-sdk-ruby/util/http_helper.rb:3:in `<module:OSTSdk>'
	from /Library/Ruby/Gems/2.3.0/gems/ost-sdk-ruby-0.9.2/lib/ost-sdk-ruby/util/http_helper.rb:1:in `<top (required)>'
	from /Library/Ruby/Gems/2.3.0/gems/ost-sdk-ruby-0.9.2/lib/ost-sdk-ruby/util.rb:4:in `require_relative'
	from /Library/Ruby/Gems/2.3.0/gems/ost-sdk-ruby-0.9.2/lib/ost-sdk-ruby/util.rb:4:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/ost-sdk-ruby-0.9.2/lib/ost-sdk-ruby.rb:7:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from (irb):1
	from /usr/bin/irb:11:in `<main>'`

**Comment by blynnXPO** [comment]
I only have ruby installed `ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin17]` and the ost sdk package.  Is it possible I'm missing something?

**Comment by puneet-khushwani-eth** [comment]
We are working on the fix of this issue ( filed here : #5 ). 

In the meanwhile please install rack manually using below command:

sudo gem install rack

**Comment by blynnXPO** [comment]
thanks that worked, is there any guide on getting started with the node js authentication? I've worked with node before, but I'm looking to find the correct repo and dependencies to get started.
https://dev.ost.com/docs/api_authentication.html

**Comment by puneet-khushwani-eth** [comment]
This is fixed with the release of 0.9.3
