### ISSUE TITLE
Declare rack in Gemspec

### ISSUE THREAD

**Issue by jasonklein** [OpenSTFoundation/ost-sdk-ruby#5]
A dependency, rack (https://github.com/OpenSTFoundation/ost-sdk-ruby/blob/master/lib/ost-sdk-ruby/util/http_helper.rb#L12), should be declared in the Gemspec.

**Comment by mirrormirage0** [comment]
# Problem

ubuntu@neo-gcp-01-ubuntu16:~/OST$ sudo irb
irb(main):001:0> require('ost-sdk-ruby')
LoadError: cannot load such file -- rack
from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in require' from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:inrequire'
from /var/lib/gems/2.3.0/gems/ost-sdk-ruby-0.9.2/lib/ost-sdk-ruby/util/http_helper.rb:12:in <class:HTTPHelper>' from /var/lib/gems/2.3.0/gems/ost-sdk-ruby-0.9.2/lib/ost-sdk-ruby/util/http_helper.rb:5:in<module:Util>'
from /var/lib/gems/2.3.0/gems/ost-sdk-ruby-0.9.2/lib/ost-sdk-ruby/util/http_helper.rb:3:in <module:OSTSdk>' from /var/lib/gems/2.3.0/gems/ost-sdk-ruby-0.9.2/lib/ost-sdk-ruby/util/http_helper.rb:1:in<top (required)>'
from /var/lib/gems/2.3.0/gems/ost-sdk-ruby-0.9.2/lib/ost-sdk-ruby/util.rb:4:in require_relative' from /var/lib/gems/2.3.0/gems/ost-sdk-ruby-0.9.2/lib/ost-sdk-ruby/util.rb:4:in<top (required)>'
from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in require' from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:inrequire'
from /var/lib/gems/2.3.0/gems/ost-sdk-ruby-0.9.2/lib/ost-sdk-ruby.rb:7:in <top (required)>' from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:inrequire'
from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in rescue in require' from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:inrequire'
from (irb):1
from /usr/bin/irb:11:in `<main>'



# Solution 
**# sudo gem install rack**

**Comment by jeez07z** [comment]
Also, to use the gem ‘rack’ - ruby version 2.2.x is required
