### ISSUE TITLE
Transactions generated using API do not show up on the Dashboard

### ISSUE THREAD

**Issue by mirrormirage0** [OpenSTFoundation/ost-sdk-ruby#6]
This probably is a UI issue.

I was able to create a Transaction called "Like" as per the instructions and execute the transaction.
The transaction does execute successfully because the User's Tokens are getting updated in UI.

However, the newly generated Transaction Count does not appear in the graph or the dashboard.

**Comment by jasonklein** [comment]
@mirrormirage0: as OST KIT⍺ is temporarily unavailable to improve performance and address matters like the one you note in this issue, I am going to close this issue.
